server:
  port: 8080
spring:
  application:
    name: material_take_out
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: cmysr1030
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false #是否开启二级缓存
  global-config:
    db-config:
      id-type: ASSIGN_ID #主键策略
      update-strategy: not_null #更新策略
      #logic-delete-field: flag 用于标志逻辑删除的字段名,类型为int或boolean
      #logic-delete-value: 1 (逻辑已删除,默认为1)
      #logic-not-delete-value: 0 (逻辑未删除,默认为0)
  #type-aliases-package: org.example.reggie.entity #别名扫描包
  #mapper-locations: "classpath*:/mapper/**/*.xml" #Mapper.xml文件地址(默认值)
